// ================================================================
// TestCase Studio — Playwright Script
// Name  : Recorded_Test
// Date  : 6/9/2026, 11:33:37 AM
// Steps : 5
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node Recorded_Test.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 5 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('http://localhost/assign2version4/login.php');

  // Step 2: Click on "bodyElement"
  // Playwright: page.locator('body')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//body') },
    { label: 'CSS (primary)', loc: page.locator('body') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//body)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('body:nth-of-type(1)') }
  ], 'Click on "bodyElement"');
  await el_2.click();

  // Step 3: Enter "Admin" into "Username:"
  // Playwright: page.locator('#Username')
  const el_3 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'Username\']') },
    { label: 'CSS (primary)', loc: page.locator('#Username') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "Admin" into "Username:"');
  await el_3.fill(`Admin`);

  // Step 4: Enter "******" into "Password:"
  // Playwright: page.locator('#Password')
  const el_4 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'Password\']') },
    { label: 'CSS (primary)', loc: page.locator('#Password') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(2)') }
  ], 'Enter "******" into "Password:"');
  await el_4.fill(`******`);

  // Step 5: Click on "Login"
  // Playwright: page.locator('input[value=\'Login\']')
  const el_5 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@value=\'Login\']') },
    { label: 'CSS (primary)', loc: page.locator('input[value=\'Login\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[4]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Click on "Login"');
  await el_5.click();

  console.log('\n✓ All 5 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});