// ================================================================
// TestCase Studio — Playwright Script
// Name  : Recorded_Test
// Date  : 6/9/2026, 11:24:05 AM
// Steps : 19
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node Recorded_Test.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 19 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('http://localhost/assign2version4/admindashboard.php');

  // Step 2: Click on "bodyElement"
  // Playwright: page.locator('body')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//body') },
    { label: 'CSS (primary)', loc: page.locator('body') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//body)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('body:nth-of-type(1)') }
  ], 'Click on "bodyElement"');
  await el_2.click();

  // Step 3: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 4: Click on "📋 View Customer Enquiries"
  // Playwright: page.locator('a[href=\'view_enquiry.php\']')
  const el_4 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[contains(text(),\'📋 View Customer Enquiries\')]') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'view_enquiry.php\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[11]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'📋 View Customer Enquiries\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "📋 View Customer Enquiries"');
  await el_4.click();

  // Step 5: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 6: Click on "Mark as Resolved"
  // Playwright: page.locator('a[href=\'view_enquiry.php?resolve_id=2\']')
  const el_6 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Mark as Resolved\']') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'view_enquiry.php?resolve_id=2\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[11]') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Mark as Resolved"');
  await el_6.click();

  // Step 7: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 8: Click on "Back to Dashboard"
  // Playwright: page.locator('.back-dashboard-btn')
  const el_8 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Back to Dashboard\']') },
    { label: 'CSS (primary)', loc: page.locator('.back-dashboard-btn') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[11]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'BACK TO DASHBOARD\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Back to Dashboard"');
  await el_8.click();

  // Step 9: Click on "📦 View Customer Orders"
  // Playwright: page.locator('a[href=\'manage_orders.php\']')
  const el_9 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[contains(text(),\'📦 View Customer Orders\')]') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'manage_orders.php\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[12]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'📦 View Customer Orders\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "📦 View Customer Orders"');
  await el_9.click();

  // Step 10: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 11: Click on "Fairy Castle Cactus - 1,Succulent Pruning Shears - 1"
  // Playwright: page.locator('body > main:nth-child(4) > table:nth-child(3) > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(4)')
  const el_11 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tbody/tr[2]/td[4]') },
    { label: 'CSS (primary)', loc: page.locator('body > main:nth-child(4) > table:nth-child(3) > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(4)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//td)[13]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//td[normalize-space()=\'Fairy Castle Cactus - 1, Succulent Pruning Shears - 1\']') },
    { label: 'nth-of-type CSS', loc: page.locator('td:nth-of-type(4)') }
  ], 'Click on "Fairy Castle Cactus - 1,Succulent Pruning Shears - 1"');
  await el_11.click();

  // Step 12: Right click on "Fairy Castle Cactus - 1,Succulent Pruning Shears - 1"
  // Playwright: page.locator('body > main:nth-child(4) > table:nth-child(3) > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(4)')
  const el_12 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tbody/tr[2]/td[4]') },
    { label: 'CSS (primary)', loc: page.locator('body > main:nth-child(4) > table:nth-child(3) > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(4)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//td)[13]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//td[normalize-space()=\'Fairy Castle Cactus - 1, Succulent Pruning Shears - 1\']') },
    { label: 'nth-of-type CSS', loc: page.locator('td:nth-of-type(4)') }
  ], 'Right click on "Fairy Castle Cactus - 1,Succulent Pruning Shears - 1"');
  await el_12.click({ button: 'right' });

  // Step 13: Enter "Succulent Pruning Shears" into "Search by Product Name"
  // Playwright: page.locator('input[placeholder=\'Search by Product Name\'][name=\'search_name\']')
  const el_13 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@name=\'search_name\']') },
    { label: 'CSS (primary)', loc: page.locator('input[placeholder=\'Search by Product Name\'][name=\'search_name\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "Succulent Pruning Shears" into "Search by Product Name"');
  await el_13.fill(`Succulent Pruning Shears`);

  // Step 14: Click on "Search"
  // Playwright: page.locator('input[value=\'Search\']')
  const el_14 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@value=\'Search\']') },
    { label: 'CSS (primary)', loc: page.locator('input[value=\'Search\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Click on "Search"');
  await el_14.click();

  // Step 15: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 16: Click on "Pending"
  // Playwright: page.locator('button[name=\'mark_delivered\']')
  const el_16 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[normalize-space()=\'Pending\']') },
    { label: 'CSS (primary)', loc: page.locator('button[name=\'mark_delivered\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Pending"');
  await el_16.click();

  // Step 17: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 18: Click on "Back to Dashboard"
  // Playwright: page.locator('.back-dashboard-btn')
  const el_18 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Back to Dashboard\']') },
    { label: 'CSS (primary)', loc: page.locator('.back-dashboard-btn') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[14]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'BACK TO DASHBOARD\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Back to Dashboard"');
  await el_18.click();

  // Step 19: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  console.log('\n✓ All 19 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});